export const OPEN_EVENT_POPUP = "OPEN_EVENT_POPUP";
export const ADD_COMMENT_TO_EVENT = "ADD_COMMENT_TO_EVENT";
export const ADD_DESCRIPTION_TO_EVENT = "ADD_DESCRIPTION_TO_EVENT";

export const ADD_EVENT_REQUEST = "ADD_EVENT_REQUEST";
export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_FAIL = "ADD_EVENT_FAIL";

export const ADD_LABEL_TO_SELECTED_LABELS_LIST = "ADD_LABEL_TO_SELECTED_LABELS_LIST";

export const SET_SELECTED_TASK = "SET_SELECTED_TASK";

